services:
  app:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - app-network

  mongo:
    image: mongo:8.0.0-noble
    restart: always
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    env_file:
      - .env
    networks:
      - app-network

  migrate-mongo:
    image: node:slim
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    command: >
      sh -c "npm install && npx migrate-mongo up"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: